# Generated by Django 3.2.8 on 2021-10-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PositionModel',
            new_name='Position',
        ),
    ]
